let C = 107;
let F = (C * 1.8) + 32;
console.log(F);
let month = 30;
let hours = month * 4;
let minutes = hours * 60;
console.log(hours);
console.log(minutes);
let hp = 100; 
let stamina = 300;
console.log(hp - 30);
console.log(stamina * 0.79);
let shop = 300;
console.log(shop * 0.9);
let number = 14.88;
console.log(Math.floor(number));
let firstString = "14.1414242apsdasdadw";
console.log(Number.parseFloat(firstString));
let secondString = "14888ss";
console.log(Number.parseFloat(secondString));
let sqrt = 2025;
console.log(Math.sqrt(sqrt));